In [1]:
import pandas as pd
import json

with open('q_table.json') as fh:
    qt = json.load(fh)


rows = []
for i, (k, v) in enumerate(qt.items()):
    for action, q_ in v.items():
        row = [k, action, q_]
        rows.append(row)

In [2]:
df = pd.DataFrame(rows, columns=['state', 'action', 'q'])

In [3]:
df.query("state == '1XXX10XX1010'")

              state action     q
25299  1XXX10XX1010    1|0 -0.40
25300  1XXX10XX1010    1|5 -0.40
25301  1XXX10XX1010    0|2 -2.71
25302  1XXX10XX1010    1|2 -1.24
25303  1XXX10XX1010    0|4 -1.90
25304  1XXX10XX1010    1|4 -1.90
25305  1XXX10XX1010    0|1 -1.00
25306  1XXX10XX1010    0|0  1.00
25307  1XXX10XX1010    1|1  0.38

In [40]:
df_ = df.groupby("state")['action'].count().reset_index().query("action == 12")

In [47]:
df[df['state'].str.startswith('0')].sort_values(by='q', ascending=False).head(50)

             state  action      q
78057    0X29XXXK0  1|None  1.235
132530  0X6XXXK100  1|None  1.000
128379  0X4XXX9100  1|None  1.000
23195    04QXXXX80  1|None  1.000
37413    0Q4XXXXJ0  0|None  1.000
89789   0X8XXX3100  0|None  1.000
168627   0XX6XXAJ0  1|None  1.000
94094    0XK5XXX50  0|None  1.000
32460   0XXXX62100  0|None  1.000
114259   0XAX9XXA0  1|None  1.000
128078   0X72XXX80  1|None  1.000
130281   0XXXQ6XA0  0|None  1.000
16722   0X2XX6X100  1|None  1.000
137992   0XX2XX240  1|None  1.000
68458    0X28X2X50  1|None  1.000
61007    0XX5X2XJ0  0|None  1.000
87121    0X9XX2XA0  1|None  1.000
150755   0X8XX4X70  0|None  1.000
37987   08X10AXX30  0|None  1.000
45836    0XXX5X480  1|None  1.000
65204   0XXXQ10620  1|None  1.000
145196  0JX8XXX100  0|None  1.000
29220   010XX59X70  0|None  1.000
89914    04XXXQX30  0|None  1.000
16832    0XXX9X750  0|None  1.000
49146    0A5XXXXK0  0|None  1.000
40988   0JXX10XXQ0  1|None  1.000
150298   0X7XX8XQ0  1|None  1.000
147223   0XXXKX390  1|None  1.000
89853   0X8X4XX100  0|None  1.000
3524     06XXJX250  0|None  1.000
99918    0XKXXX720  1|None  1.000
17734    0XX6X7XA0  1|None  1.000
31531    03XX7XXA0  0|None  1.000
106922   0X2X5XX60  1|None  0.920
15840   0310XXJXQ0  1|None  0.900
66686    0K8X2XX80  1|None  0.900
45629    08X7XXX20  0|None  0.900
52807   0X5XXX1040  1|None  0.900
170524  0XXX810KK0  1|None  0.900
80929   0KX510XXQ0  0|None  0.900
54614    05XX3XXK0  0|None  0.900
137677   0XX45XX70  0|None  0.900
1566    0K106X8XK0  1|None  0.900
117368   0X2XX6KQ0  0|None  0.900
42010    0X6XAXX60  1|None  0.810
55014    02X56XX20  0|None  0.800
80231    0X597XX80  1|None  0.800
28380    039XXXXJ0  1|None  0.800
102829  0X910XXXQ0  1|None  0.800